# Generated by Django 2.0.13 on 2019-09-18 12:02

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('usn', models.TextField(blank=True, max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendRegister',
            fields=[
                ('arid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, default='dept_name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_state', models.BooleanField(default=True)),
                ('e_title', models.CharField(default='title', max_length=255)),
                ('e_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Event Date')),
                ('e_start_time', models.TimeField(default='12:00:00')),
                ('e_end_time', models.TimeField(blank=True, default='12:00:00', null=True)),
                ('e_venue', models.CharField(default='Venue', max_length=120)),
                ('e_description', models.TextField(blank=True)),
                ('e_score', models.IntegerField()),
                ('e_registration_link', models.CharField(blank=True, max_length=255, null=True)),
                ('e_photos_link', models.CharField(blank=True, max_length=255, null=True)),
                ('e_medium_link', models.CharField(blank=True, max_length=255, null=True)),
                ('e_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('n_id', models.IntegerField(primary_key=True, serialize=False)),
                ('n_title', models.CharField(default='title', max_length=255)),
                ('n_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 18, 12, 2, 21, 216756))),
                ('n_image', models.ImageField(default='news/no-img.jpg', upload_to='images/')),
                ('n_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('ut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ut_name', models.CharField(default='type', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='attendregister',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Events'),
        ),
        migrations.AddField(
            model_name='attendregister',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dept'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserType'),
        ),
    ]
