# Generated by Django 2.0.10 on 2019-11-07 08:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_state', models.BooleanField(default=True)),
                ('p_title', models.CharField(default='title', max_length=100)),
                ('p_image', models.ImageField(default='projects/no-img.jpg', upload_to='images/projects/')),
                ('p_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 7, 8, 6, 40, 857839))),
                ('p_desc', models.CharField(default='description', max_length=500)),
                ('p_medium_link', models.CharField(default='https://www.medium.com', max_length=250)),
                ('p_github_link', models.CharField(default='https://www.github.com', max_length=250)),
                ('p_apply_link', models.CharField(default='https://www.google.com', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeRegister',
            fields=[
                ('ut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ut_name', models.CharField(default='type', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visioneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('visioneerEmailAddress', models.EmailField(max_length=100, unique=True, verbose_name='username@visioneer.atria.edu')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('passwordhashfunction', models.CharField(default='MD%', max_length=100)),
                ('orgunitpath', models.CharField(default='org', max_length=100)),
                ('recoveryemail', models.EmailField(max_length=100, verbose_name='Recovery Email')),
                ('recoveryphone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone Number')),
                ('homeaddress', models.CharField(max_length=100, verbose_name='Primary Address')),
                ('employeeid', models.CharField(max_length=100, verbose_name='USN')),
                ('departement', models.CharField(default='title', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_t',
        ),
        migrations.AddField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 7, 8, 6, 40, 856144)),
        ),
        migrations.AddField(
            model_name='events',
            name='e_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='n_desc',
            field=models.CharField(default='title', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='n_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='ut_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='arid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 7, 8, 6, 40, 856850)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_image',
            field=models.ImageField(default='news/no-img.jpg', upload_to='images/news/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
