# Generated by Django 2.0.13 on 2019-09-19 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190918_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeRegister',
            fields=[
                ('ut_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('ut_name', models.CharField(default='type', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 4, 42, 17, 55952)),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
