# Generated by Django 2.0.10 on 2020-01-17 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200117_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 17, 20, 17, 23, 491901)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 17, 20, 17, 23, 492823)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 17, 20, 17, 23, 494222)),
        ),
    ]
