# Generated by Django 2.2.5 on 2019-09-15 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190915_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ut',
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 9, 35, 22, 586626)),
        ),
    ]
