# Generated by Django 2.0.13 on 2019-09-19 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190919_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 4, 48, 18, 112777)),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertyperegister',
            name='ut_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
