# Generated by Django 2.2.5 on 2019-09-15 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190915_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ut',
        ),
        migrations.AddField(
            model_name='user',
            name='user_t',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.UserType'),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 9, 37, 29, 750615)),
        ),
    ]
