# Generated by Django 2.2.5 on 2019-09-15 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190915_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 9, 52, 1, 660893)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserType'),
        ),
    ]
