# Generated by Django 2.0.13 on 2019-09-19 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190919_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='n_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 12, 4, 40, 918242)),
        ),
    ]
