# Generated by Django 2.2.5 on 2019-09-15 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190915_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 9, 57, 52, 766644)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserType'),
        ),
    ]
