# Generated by Django 2.0.13 on 2019-09-19 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190919_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_t',
        ),
        migrations.AddField(
            model_name='user',
            name='ut_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 12, 40, 35, 848739)),
        ),
    ]
