# Generated by Django 2.0.13 on 2019-09-24 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190919_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='n_desc',
            field=models.CharField(default='title', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 24, 18, 19, 50, 93794)),
        ),
    ]
