# Generated by Django 2.0.13 on 2019-09-26 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190924_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 5, 9, 54, 79854)),
        ),
        migrations.AddField(
            model_name='events',
            name='e_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 5, 9, 54, 80964)),
        ),
    ]
