# Generated by Django 2.0.13 on 2019-09-26 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190926_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 6, 10, 12, 590628)),
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='arid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 6, 10, 12, 591494)),
        ),
    ]
