# Generated by Django 2.0.10 on 2019-09-26 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190926_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 38, 53, 343947)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 38, 53, 345209)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 38, 53, 346553)),
        ),
    ]
