# Generated by Django 2.0.10 on 2019-09-26 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190926_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_apply_link',
            field=models.CharField(default='https://www.google.com', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='p_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 51, 9, 541101)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 51, 9, 542344)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 26, 17, 51, 9, 543526)),
        ),
    ]
