# Generated by Django 2.0.10 on 2019-11-05 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191105_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visioneer',
            name='buildingid',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='changepasswordatnextsignin',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='costcenter',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='employeetitle',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='employeetype',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='floorname',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='floorsection',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='hphone',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='hsecondaryemail',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='manageremail',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='mphone',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='newprimaryemail',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='newstatus',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='workaddress',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='wphone',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='wsecondaryemail',
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 4, 17, 32, 704177)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 4, 17, 32, 705058)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 4, 17, 32, 706140)),
        ),
    ]
