# Generated by Django 2.0.10 on 2019-11-05 09:45

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191105_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visioneer',
            old_name='emailaddress',
            new_name='visioneerEmailAddress',
        ),
        migrations.RemoveField(
            model_name='visioneer',
            name='rphone',
        ),
        migrations.AddField(
            model_name='visioneer',
            name='recoveryphone',
            field=phone_field.models.PhoneField(blank=True, help_text='Recovery phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 9, 45, 53, 628679)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 9, 45, 53, 629423)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 9, 45, 53, 630545)),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='orgunitpath',
            field=models.CharField(default='org', max_length=100),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='passwordhashfunction',
            field=models.CharField(default='MD%', max_length=100),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='recoveryemail',
            field=models.EmailField(default='recoveryemail', max_length=100),
        ),
    ]
