# Generated by Django 2.0.10 on 2019-11-05 10:26

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191105_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendregister',
            name='a_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 10, 26, 40, 664784)),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 10, 26, 40, 665768)),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 10, 26, 40, 667304)),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='employeeid',
            field=models.CharField(max_length=100, verbose_name='USN'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='homeaddress',
            field=models.CharField(max_length=100, verbose_name='Primary Address'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='recoveryemail',
            field=models.EmailField(max_length=100, verbose_name='Recovery Email'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='recoveryphone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='visioneer',
            name='visioneerEmailAddress',
            field=models.EmailField(max_length=100, unique=True, verbose_name='username@visioneer.atria.edu'),
        ),
    ]
